### ISSUE TITLE
Editing a module does not reject an empty name or number

### ISSUE THREAD

**Issue by joshuadargan** [edugator-cise/edugator-staff-backend#78]
**Describe the bug**
Editing a module allows you to give a module an empty name.

**To Reproduce**
1. Go to Modules
2. Click on Edit
3. delete the name and number

**Expected behavior**
An invalid name or number should be rejected. Probably if either one is invalid, the change should fail.

**Screenshots**
![image](https://user-images.githubusercontent.com/40403340/140574129-f9e6e0d4-cff4-4512-adaa-56cff36ceadd.png)

**Comment by marcgabe15** [comment]
Fixed
