### ISSUE TITLE
Build command is required when it should be allowed to be empty

### ISSUE THREAD

**Issue by joshuadargan** [edugator-cise/edugator-staff-backend#83]
Describe the bug

To Reproduce

1. Go to create a problem
2. Fill out the problem
3. Leave build command empty
4. Submit
5. See error

Expected behavior
Should allow empty build commands.

![image](https://user-images.githubusercontent.com/40403340/140785444-eb555689-f52c-4c90-8449-c3089a1000e6.png)

**Comment by marcgabe15** [comment]
Fixed
